/*
 * generated by Xtext
 */
package org.casualintellect.ui.contentassist

import org.casualintellect.ui.contentassist.AbstractCasualIntellectProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CasualIntellectProposalProvider extends AbstractCasualIntellectProposalProvider {
}
