/*
 * generated by Xtext
 */
package org.casualintellect.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.casualintellect.ui.internal.CasualIntellectActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CasualIntellectExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CasualIntellectActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CasualIntellectActivator.getInstance().getInjector(CasualIntellectActivator.ORG_CASUALINTELLECT_CASUALINTELLECT);
	}
	
}
