/*
 * generated by Xtext
 */
package org.casualintellect.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CasualIntellectUiModule extends org.casualintellect.ui.AbstractCasualIntellectUiModule {
	public CasualIntellectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
